ENVIRONMENT:
  NUM_GPU: 4
  DATA_BASE_DIR: 'FlareSeg/dataset/'
  IS_SMOKE_TEST: False

DATA_LOADER:
  TRAIN_VAL_FOLD: 1
  TRAIN_DB_FILE: 'db/seg_train_fold_'
  VAL_DB_FILE: 'db/seg_val_fold_'
  TEST_DB_FILE: 'db/seg_raw_test'
  BAD_CASE_SERIES_IDS_TXT: 'FlareSeg/dataset/file_list/lesion_case.txt'
  BAD_CASE_AUGMENT_TIMES: 3
  LABEL_INDEX: [1, 2, 3, 4]
  LABEL_NUM: [1, 2, 1, 1]
  LABEL_NAME: ['Liver', 'Kidney', 'Spleen', 'Pancreas']
  IS_COARSE: False
  IS_NORMALIZATION_HU: True
  IS_NORMALIZATION_DIRECTION: True
  WINDOW_LEVEL: [-325, 325]
  EXTEND_SIZE: 20
  NUM_WORKER: 7
  BATCH_SIZE: 5
  FIVE_FOLD_LIST: [1]

DATA_AUGMENT:
  IS_ENABLE: True
  IS_RANDOM_FLIP: False
  IS_RANDOM_ROTATE: False
  IS_RANDOM_SHIFT: False
  IS_RANDOM_CROP_TO_LABELS: True
  IS_ELASTIC_TRANSFORM: False
  IS_CHANGE_ROI_HU: True
  IS_ADD_GAUSSIAN_NOISE: False
  ROI_HU_RANGE: [-200, 200]
  ROTATE_ANGLE: [-10, 10]
  MAX_EXTEND_SIZE: 40
  SHIFT_MAX_RATIO: 0.3

COARSE_MODEL:
  META_ARCHITECTURE: 'UNet'
  INPUT_SIZE: [160, 160, 160]
  NUM_CLASSES: 4
  NUM_CHANNELS: [8, 16, 32, 64, 128]
  ENCODER_CONV_BLOCK: 'ResFourLayerConvBlock'
  DECODER_CONV_BLOCK: 'ResTwoLayerConvBlock'
  CONTEXT_BLOCK: None
  NUM_DEPTH: 4
  IS_PREPROCESS: True
  IS_POSTPROCESS: False
  IS_DYNAMIC_EMPTY_CACHE: False
  WEIGHT_DIR: None

FINE_MODEL:
  META_ARCHITECTURE: 'EfficientSegNet'
  AUXILIARY_TASK: False
  AUXILIARY_CLASS: 1
  INPUT_SIZE: [192, 192, 192]
  NUM_CLASSES: 4
  NUM_BLOCKS: [2, 2, 2, 2, 2]
  DECODER_NUM_BLOCK: 1
  NUM_CHANNELS: [16, 32, 64, 128, 256]
  ENCODER_CONV_BLOCK: 'ResBaseConvBlock'
  DECODER_CONV_BLOCK: 'AnisotropicConvBlock'
  CONTEXT_BLOCK: 'AnisotropicAvgPooling'
  NUM_DEPTH: 4
  IS_PREPROCESS: True
  IS_POSTPROCESS: True
  IS_DYNAMIC_EMPTY_CACHE: False
  WEIGHT_DIR: None

TRAINING:
  OPTIMIZER:
    LR: 1e-3
  SCHEDULER:
    TOTAL_EPOCHS: 200
  SAVER:
    SAVER_DIR: './output/train'
  IS_DISTRIBUTED_TRAIN: True
  IS_APEX_TRAIN: True
  LOSS: 'dice'
  METRIC: 'dice'

TESTING:
  COARSE_MODEL_WEIGHT_DIR: '../model_weights/base_coarse_model/best_model.pt'
  FINE_MODEL_WEIGHT_DIR: None
  NUM_WORKER: 3
  BATCH_SIZE: 1
  IS_FP16: True
  SAVER_DIR: './output/test'
  IS_SAVE_MASK: True
  IS_POST_PROCESS: True
  OUT_RESAMPLE_MODE: 3
